name: Remove Leading and Trailing Spaces

on:
  push:
    branches:
      - '**'  # Triggers on push to any branch

jobs:
  trim-spaces:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Trim leading/trailing spaces from all files
      - name: Trim spaces from all files
        run: |
          # Find all files and use sed to remove leading/trailing spaces
          find . -type f -not -path "./.git/*" -exec sed -i -e 's/^[ \t]*//' -e 's/[ \t]*$//' {} \;

      # Configure Git user
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Check for changes and commit if needed
      - name: Check for changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "Changes detected, committing..."
            git add .
            git commit -m "Remove leading and trailing spaces"
          else
            echo "No changes detected."
      
      # Push changes to the same branch that triggered the workflow
      - name: Push changes
        run: |
          branch=$(echo "${GITHUB_REF#refs/heads/}")
          git push origin "$branch"
