name: Remove Leading and Trailing Spaces on Most Recent Branch

on:
  push:
    branches:
      - '**'  # Triggers on push to any branch

jobs:
  trim-spaces:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      # Checkout the repository and fetch all branches
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all branches so we can check out the most recent one

      # Get the most recent branch and check it out
      - name: Checkout the most recent branch
        run: |
          # Get the most recent branch (excluding HEAD)
          branch=$(git for-each-ref --sort=-committerdate refs/heads/ --format='%(refname:short)' | head -n 1)
          echo "Most recent branch is $branch"
          git checkout "$branch"

      # Trim leading/trailing spaces from all files
      - name: Trim spaces from all files
        run: |
          # Find all files and use sed to remove leading/trailing spaces
          find . -type f -not -path "./.git/*" -exec sed -i -e 's/^[ \t]*//' -e 's/[ \t]*$//' {} \;

      # Configure Git user
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # Check for changes and commit if needed, explicitly using 'fi'
      - name: Check for changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Changes detected, committing..."
            git add .
            git commit -m "Remove leading and trailing spaces"
          else
            echo "No changes detected."
          fi

      # Push changes to the most recent branch
      - name: Push changes
        run: |
          branch=$(git rev-parse --abbrev-ref HEAD)
          git push origin "$branch"
